### ISSUE TITLE
Loading dll issue in TestGLES_SKIA_GLFW Example

### ISSUE THREAD

**Issue by azeem20** [PaintLab/PixelFarm#23]
1- TestGLES_SKIA_GLFW  has the dependency of PixelFarm.Drawing.GLES2.dll 
2-  PixelFarm.Drawing.GLES2  has the dependency of  PixelFarm.Typography.dll 
3- PixelFarm.Typography hasthe  dependency of Typography.Contours.dll
4- Typography.Contours has the dependency of Typography.OpenFont.dll
5- Typography.OpenFont has some kind of syntex error and unable to build

![image](https://user-images.githubusercontent.com/26283064/38913685-780a5d3a-42f5-11e8-8e97-8038762bdae6.png)

**Comment by prepare** [comment]
@azeem20,

Sorry for late reply (I see it today)

from your picture,  code line 19 (yellow mark)
It use new 'C# 7 out'
see more : https://blogs.msdn.microsoft.com/dotnet/2016/08/24/whats-new-in-csharp-7-0/


---
It can be compiled with VS2017 .
This is from my machine.

![err01](https://user-images.githubusercontent.com/7447159/39402506-350da9d0-4b8b-11e8-82f4-98d0c22b4ec8.png)
_pic 1: Typography.OpenFont 's ScriptList.cs_

---


If you need to use the old version of VS.

please change it to the old syntax like this ...
![err02](https://user-images.githubusercontent.com/7447159/39402542-368b8bbe-4b8c-11e8-971a-ffac1383f843.png)

_pic 2: change from pic1_

---

I accept this syntax too. 

make it work with your project.
and welcome your pull request :)
