### ISSUE TITLE
About subpixel rendering

### ISSUE THREAD

**Issue by Happypig375** [PaintLab/PixelFarm#36]
Do I need to use the agg-sharp backend for subpixel rendering? Is any other backend unable to do this? Is the agg-sharp backend inside the Backend.Paintfx project?

**Comment by prepare** [comment]
**Subpixel rendering** may be implemented by various techniques.

This feature is not found in original agg-sharp.
so I implement this with the Maxim's agg technique (https://github.com/PaintLab/PixelFarm/issues/3#issuecomment-287991561).

so my technique is based on Maxim's agg technique

> Do I need to use the agg-sharp backend for subpixel rendering?

Yes, 
I provide  2 examples

1) Pure software subpixel rendering  
    (I call it _SubPixelLcdEffect_ ,
     follow the detail here => https://github.com/PaintLab/PixelFarm/blob/dev/src/PixelFarm/PixelFarm.Drawing/7_CpuBlitPainter/RenderSurface/AggRenderSurface.cs#L281)

2) Texture-based hardware-accelerated GLES (see https://github.com/PaintLab/PixelFarm/issues/3)
    (by create 'inverted RGBA' subpixel-rendering glyph texture, and rendering 3 times in 
    different color channels,
   follow the detail here => 
https://github.com/PaintLab/PixelFarm/blob/dev/src/PixelFarm/PixelFarm.DrawingGL/DrawingGL/RenderSuface/GLRenderSurface.cs#L507
   )

**Comment by prepare** [comment]
How to draw a '_crisp_' glyph is not depend on 'subpixel Lcd-Effect' only.

It is also depend on the 'pixel-position' of a glyph too. => this is important.

please see https://github.com/PaintLab/PixelFarm/issues/16#issue-284363097 
and follow the detail.
( you can see that pic 1, is not rendered with subpixel rendering tech, it is rendered with
blue color fill over _grey-scale_ stencil glyph, but in _minor_ different position (x,y) )

**Comment by prepare** [comment]
What is Backend.Paintfx project ?

It is a core of an old open source version of Paint.NET (Pdn) project.
I try to integrate its features to the agg canvas surface
