### ISSUE TITLE
HAPPY NEW YEAR 2019

### ISSUE THREAD

**Issue by prepare** [PaintLab/PixelFarm#49]
BRAVE and FOCUS

:)

**Comment by Happypig375** [comment]
yoooooo

**Comment by Happypig375** [comment]
Typography reached 100 stars! 🎉

**Comment by prepare** [comment]
![typo100](https://user-images.githubusercontent.com/7447159/51457177-f41ce880-1d82-11e9-82be-913acc7e8a1e.png)
_Selfie!_
