### ISSUE TITLE
Clean build fails - many missing files in Typography project

### ISSUE THREAD

**Issue by garethhayter** [PaintLab/PixelFarm#50]
I have the latest versions of PixelFarm and Typograhy projects, but when building PixelFarm I get many errors about missing files in the Typography projects eg:

- Typography\PixelFarm.Typography\1.1_Drawing_Fonts\GlyphSvgStore.cs' could not be found.
- Typography\Typography.OpenFont\Tables.BitmapAndSvgFonts\EBSC.cs' could not be found.

It seems like the latest versions of the projects are not aligned. Any suggestions for getting a working build?

Alternatively, is there anywhere I can get binaries of PixelFarm that will work with HtmlRenderer, as that's what I'm really wanting.

**Comment by prepare** [comment]
Hello, sorry for late reply


Today, I push latest PixelFarm/HtmlRenderer dev to master,

please build PixelFarm with https://github.com/PaintLab/PixelFarm/commit/3d3cc8644f1424dc401c34e8517b61685c94a5a0

and HtmlRenderer, use latest https://github.com/LayoutFarm/HtmlRenderer/commit/e9bbc3d2696cc3066493bd41bbe385bc81d3536f


and for **Typography**, please use latest branch => https://github.com/LayoutFarm/Typography/tree/dev_for_latest_pixelfarm

**Comment by zwcloud** [comment]
> please build PixelFarm with 3d3cc86
> 
> and HtmlRenderer, use latest LayoutFarm/HtmlRenderer@e9bbc3d
> 
> and for Typography, please use latest branch => https://github.com/LayoutFarm/Typography/tree/dev_for_latest_pixelfarm

Have you updated this versions in https://github.com/PaintLab/pxdev?

**Comment by prepare** [comment]
please visit : https://github.com/LayoutFarm/HtmlRenderer.Build
